---

- name: Update the cache.........
  apt:
    update_cache: yes


- name: Installing libpam-google-authenticator ...
  apt: name=libpam-google-authenticator state=installed
  

- name: run google authenticator command
  shell: yes  | google-authenticator
  register: prompt
  become_user: {{vagrant_user}}

- debug:
    var: prompt.stdout_lines

- name: Update sshd file
  lineinfile:
    path: /etc/pam.d/sshd
    backup: yes
    regexp: '^@include common-auth '
    insertafter: '^@include common-auth'
    line: '#@include common-auth'
    line: 'auth required pam_google_authenticator.so'
    insertafter: EOF
    

- name: Update sshd_config file
  lineinfile:
    path: /etc/ssh/sshd_config
    backup: yes
    regexp: '^ChallengeResponseAuthentication '
    insertafter: '^ChallengeResponseAuthentication '
    line: 'ChallengeResponseAuthentication yes'
    regexp: '^PasswordAuthentication'
    insertafter: '^PasswordAuthentication '
    line: 'PasswordAuthentication no'
    line: 'AuthenticationMethods  publickey,keyboard-interactive'
    insertafter: EOF
  notify: Restart sshd service
